### ISSUE TITLE
Can't access the import-log

### ISSUE THREAD

**Issue by seanhess** [seanhess/serials#20]
I'm getting 401 unauthorized. I created an account: `ed72f5c2-66df-4c35-a709-4aa3ff00314f`. Admin is set to true. 

Also when I click "admin" it goes back to saying `Login` instead of `Hello, Sean`. I'm not sure if that's related. 

Currently it's pretty confusing, because you can access the admin, and the import-log page, just not the actual import log.

**Comment by codedmart** [comment]
@seanhess My bad. I noted this in #18. I will fix this shortly.
