### ISSUE TITLE
Users - profile page

### ISSUE THREAD

**Issue by seanhess** [seanhess/serials#24]
Ability to update email address. Also is a prereq for #23.

**Comment by codedmart** [comment]
Unless you are doing this I can work on it. Should we validate emails on signup and change?

**Comment by seanhess** [comment]
Go for it. Definitely something we will need eventually.

**Comment by codedmart** [comment]
@seanhess I have not had time to finish this but there is some stuff in 29ad9c8d31d238e943ae1d4b3018b27bca67b31f but could be pretty behind now.
