### ISSUE TITLE
Centering content in browser

### ISSUE THREAD

**Issue by lumenwrites** [seanhess/serials#39]
I think it seems a little weird that the content is floated to the left, it would probably be better if it would be centered.

Are you new to Zurb Foundation?

I'm guessing that in main.js, instead of:

```
    <div className="row columns small-12" style={background}>
      {this.props.children}
    </div>
```

you meant something like:

```
<div className="row">
    <div className="small-12 large-12 columns" style={background}>
      {this.props.children}
    </div>
</div>
```

I don't know react.js, but I think it supposed to look like that. You can read more [here](http://foundation.zurb.com/docs/v/4.3.2/components/grid.html).

**Comment by seanhess** [comment]
Ah yes! That has been on my list. Thanks for pointing out how to fix it! Embarrassingly I'm not that new to foundation but I haven't invested in mastering it. 

Thanks again! Also PRs are always welcome.

**Comment by seanhess** [comment]
Fixed. Thanks again. I don't remember how I got it in my head that you could make the same div be a row and columns, but it was clearly wrong.
