### ISSUE TITLE
Suggest a book

### ISSUE THREAD

**Issue by seanhess** [seanhess/serials#5]
A form to have people suggest a book they don't see.

**Comment by codedmart** [comment]
Did you want to save this information in the database or something simpler like send an email to you/somewhere?

**Comment by seanhess** [comment]
Email would be great!

**Comment by seanhess** [comment]
I'm putting in a very simple "Don't see what you want? Email us at xxxx" prompt. Feel free to improve it if you want to do something cooler.

**Comment by codedmart** [comment]
That is great, I plan on trying to kick in on a few of these soon. Just been super busy :smile:
